# -*- coding: utf-8 -*-
"""final_project_stylistic_cleanup.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pJEyMsA2J5RwWRGZeGs3spSeWJTwQc16
"""

# Commented out IPython magic to ensure Python compatibility.
from google.colab import drive
drive.mount('/content/drive')

# %cd /content/drive/MyDrive
!git clone https://github.com/WillHu369/CSCI544-FinalProject.git colab_hc3_bundle

!pip install emoji

import regex as re
import emoji
import pandas as pd

"""Load in HC3 Data"""

# Load HC3 data from Github repo
from datasets import load_dataset

ds = pd.read_csv("/content/drive/MyDrive/colab_hc3_bundle/HC3-Dataset-Samples/hc3_unified_1000_seed42.csv")

"""Set up the constants needed for stylistic cleanup"""

EM_DASH_CHARS = ["\u2014", "\u2013"]  # em dash (—) and en dash (–)
EM_DASH_REPLACEMENT =  ", "

EMOJI_PATTERN = re.compile(
    "["
    "\U0001F600-\U0001F64F"  # emoticons
    "\U0001F300-\U0001F5FF"  # symbols & pictographs
    "\U0001F680-\U0001F6FF"  # transport & map
    "\U0001F1E0-\U0001F1FF"  # flags
    "\U00002700-\U000027BF"  # dingbats
    "\U0001F900-\U0001F9FF"  # supplemental symbols
    "\U00002600-\U000026FF"  # misc symbols
    "]+",
    flags=re.UNICODE
)

"""Remove & Replace Em Dashes"""

def remove_em_dashes(text):
  for c in EM_DASH_CHARS:
      # Handle spaced variants: " — " → ", "
      text = re.sub(rf'\s*{re.escape(c)}\s*', EM_DASH_REPLACEMENT, text)

  # Cleanup artifacts from replacement
  text = re.sub(r',\s*,', ',', text)   # double commas
  text = re.sub(r'^\s*,\s*', '', text) # leading comma (edge case)
  text = re.sub(r'\s{2,}', ' ', text)  # extra whitespace
  text = text.strip()
  return text

"""Remove Emojis"""

def remove_emojis(text):
  text = emoji.replace_emoji(text, replace='')  # pass 1: emoji library
  text = EMOJI_PATTERN.sub('', text)             # pass 2: regex
  text = re.sub(r'\s{2,}', ' ', text)            # clean leftover gaps
  return text.strip()

"""Remove Formatting: headers, bold, bullet/lists, italics"""

def remove_formatting(text: str) -> str:
    # Remove headers
    def header_to_prose(m):
        heading = m.group(1).strip()
        if heading and heading[-1] not in '.!?':
            heading += '.'
        return heading
    text = re.sub(r'^#{1,6}\s+(.+)', header_to_prose,
                  text, flags=re.MULTILINE)

    # Remove Horizontal rules
    text = re.sub(r'^\s*[-*=]{3,}\s*$', '', text, flags=re.MULTILINE)

    # Replace Bold text
    text = re.sub(r'\*\*([^*\n]+?)\*\*', r'\1', text)
    text = re.sub(r'__([^_\n]+?)__',     r'\1', text)

    # Bullets / list
    lines = text.split('\n')
    prose_chunks = []
    list_items   = []

    def strip_italic(s: str) -> str:
        s = re.sub(r'\*([^*\n]+?)\*', r'\1', s)
        s = re.sub(r'_([^_\n]+?)_',   r'\1', s)
        return s

    def flush_list():
        if list_items:
            prose_chunks.append('. '.join(list_items) + '.')
            list_items.clear()

    for line in lines:
        stripped = line.strip()
        bullet_match  = re.match(r'^[-*•]\s+(.+)', stripped)
        ordered_match = re.match(r'^\d+\.\s+(.+)', stripped)

        if bullet_match:
            list_items.append(strip_italic(bullet_match.group(1).strip()))
        elif ordered_match:
            list_items.append(strip_italic(ordered_match.group(1).strip()))
        else:
            flush_list()
            if stripped:
                prose_chunks.append(stripped)

    flush_list()

    # Replace Italics on non-lists
    text = ' '.join(prose_chunks)
    text = re.sub(r'\*([^*\n]+?)\*', r'\1', text)
    text = re.sub(r'_([^_\n]+?)_',   r'\1', text)

    # normalize the whitespace
    text = re.sub(r'\s{2,}', ' ', text)
    return text.strip()

def run_stylistic_cleanup(text):
  text = remove_em_dashes(text)
  text = remove_emojis(text)
  text = remove_formatting(text)
  return text

"""Apply cleanup to the small sample of HC3 Data"""

from datasets import Dataset

def apply_and_track(example: dict) -> dict:
    """
    Apply stylistic cleanup to chatgpt_answers and track
    whether each row was modified.
    """
    original_answers  = example["chatgpt_answers"]
    perturbed_answers = [run_stylistic_cleanup(ans) for ans in original_answers]

    # A row is "changed" if any of its answers were modified
    was_changed = any(
        orig != perturbed
        for orig, perturbed in zip(original_answers, perturbed_answers)
    )

    return {
        "chatgpt_answers_stylistic": perturbed_answers,
        "stylistic_changed":         was_changed,
    }

# convert into HuggingFace dataset
small_dataset = Dataset.from_pandas(ds)
small_dataset = small_dataset.map(apply_and_track)

# Summary stats
total   = len(small_dataset["chatgpt_answers"])
changed = sum(small_dataset["stylistic_changed"])
print(f"Rows changed:   {changed} / {total} ({changed/total*100:.1f}%)")
print(f"Rows unchanged: {total - changed} / {total} ({(total-changed)/total*100:.1f}%)")

# If ds is a HF Dataset, convert to dataframe first
output_df = small_dataset.to_pandas()

# Save to a new folder
import os
save_dir = "/content/drive/MyDrive/colab_hc3_bundle/Stylistic-Cleanup"
os.makedirs(save_dir, exist_ok=True)

output_df.to_csv(f"{save_dir}/hc3_sample_stylistic_cleanup.csv", index=False)

